CREATE TABLE Tbl_Kullanici (
    KullaniciId INT IDENTITY(1,1) PRIMARY KEY,
    KullaniciAdi NVARCHAR(50) NOT NULL,
    Sifre NVARCHAR(50) NOT NULL
);

CREATE TABLE Tbl_Hizmet (
    HizmetId INT IDENTITY(1,1) PRIMARY KEY,
    HizmetBaslik NVARCHAR(200) NOT NULL,
    HizmetOzet NVARCHAR(500) NOT NULL,
    HizmetDetay NVARCHAR(MAX) NOT NULL,
    HizmetResim NVARCHAR(250),
    AktifMi BIT NOT NULL DEFAULT 1
);

CREATE TABLE Tbl_Mesaj (
    MesajId INT IDENTITY(1,1) PRIMARY KEY,
    AdSoyad NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    MesajMetni NVARCHAR(MAX) NOT NULL,
    Tarih DATETIME NOT NULL DEFAULT GETDATE(),
    OkunduMu BIT NOT NULL DEFAULT 0
);
